//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 04:14:20 PM MSD 
//


package ru.tapublog.lib.gsm0348.api.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponsePacketStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResponsePacketStatus">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="POR_OK"/>
 *     &lt;enumeration value="RC_CC_DS_FAILED"/>
 *     &lt;enumeration value="CNTR_LOW"/>
 *     &lt;enumeration value="CNTR_HIGH"/>
 *     &lt;enumeration value="CNTR_BLOCKED"/>
 *     &lt;enumeration value="CIPHERING_ERROR"/>
 *     &lt;enumeration value="UNIDENTIFIED_SECURITY_ERROR"/>
 *     &lt;enumeration value="INSUFFICIENT_MEMORY"/>
 *     &lt;enumeration value="MORE_TIME"/>
 *     &lt;enumeration value="TAR_UNKNOWN"/>
 *     &lt;enumeration value="INSUFFICIENT_SECURITY_LEVEL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResponsePacketStatus")
@XmlEnum
public enum ResponsePacketStatus {

    POR_OK,
    RC_CC_DS_FAILED,
    CNTR_LOW,
    CNTR_HIGH,
    CNTR_BLOCKED,
    CIPHERING_ERROR,
    UNIDENTIFIED_SECURITY_ERROR,
    INSUFFICIENT_MEMORY,
    MORE_TIME,
    TAR_UNKNOWN,
    INSUFFICIENT_SECURITY_LEVEL;

    public String value() {
        return name();
    }

    public static ResponsePacketStatus fromValue(String v) {
        return valueOf(v);
    }

}
