//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 04:14:20 PM MSD 
//


package ru.tapublog.lib.gsm0348.api.model;

import java.util.Arrays;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SecurityHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecurityHeader">
 *   &lt;complexContent>
 *     &lt;extension base="{ru.tapublog.lib.gsm0348}PacketHeader">
 *       &lt;sequence>
 *         &lt;element name="TAR" type="{ru.tapublog.lib.gsm0348}TAR"/>
 *         &lt;element name="PaddingCounter" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="Security" type="{ru.tapublog.lib.gsm0348}Security" minOccurs="0"/>
 *         &lt;element name="Counter" type="{ru.tapublog.lib.gsm0348}Counter"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecurityHeader", propOrder = {
    "tar",
    "paddingCounter",
    "security",
    "counter"
})
@XmlSeeAlso({
    CommandPacketHeader.class,
    ResponsePacketHeader.class
})
public class SecurityHeader
    extends PacketHeader
{

    @XmlElement(name = "TAR", required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] tar;
    @XmlElement(name = "PaddingCounter")
    protected byte paddingCounter;
    @XmlElement(name = "Security", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] security;
    @XmlElement(name = "Counter", required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] counter;

    /**
     * Gets the value of the tar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getTAR() {
        return tar;
    }

    /**
     * Sets the value of the tar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAR(byte[] value) {
        this.tar = ((byte[]) value);
    }

    /**
     * Gets the value of the paddingCounter property.
     * 
     */
    public byte getPaddingCounter() {
        return paddingCounter;
    }

    /**
     * Sets the value of the paddingCounter property.
     * 
     */
    public void setPaddingCounter(byte value) {
        this.paddingCounter = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurity(byte[] value) {
        this.security = ((byte[]) value);
    }

    /**
     * Gets the value of the counter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getCounter() {
        return counter;
    }

    /**
     * Sets the value of the counter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCounter(byte[] value) {
        this.counter = ((byte[]) value);
    }

	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + Arrays.hashCode(counter);
		result = prime * result + paddingCounter;
		result = prime * result + Arrays.hashCode(security);
		result = prime * result + Arrays.hashCode(tar);
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof SecurityHeader))
			return false;
		SecurityHeader other = (SecurityHeader) obj;
		if (!Arrays.equals(counter, other.counter))
			return false;
		if (paddingCounter != other.paddingCounter)
			return false;
		if (!Arrays.equals(security, other.security))
			return false;
		if (!Arrays.equals(tar, other.tar))
			return false;
		return true;
	}

	@Override
	public String toString()
	{
		StringBuilder builder = new StringBuilder();
		builder.append("SecurityHeader [tar=");
		builder.append(Arrays.toString(tar));
		builder.append(", paddingCounter=");
		builder.append(paddingCounter);
		builder.append(", security=");
		builder.append(Arrays.toString(security));
		builder.append(", counter=");
		builder.append(Arrays.toString(counter));
		builder.append("]");
		return builder.toString();
	}

}
