//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 04:14:20 PM MSD 
//

package org.opentelecoms.gsm0348.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.opentelecoms.gsm0348.api.Util;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardProfile", propOrder = {
    "name",
    "kic",
    "kid",
    "spi",
    "tar",
    "securityBytesType",
    "signatureAlgorithm",
    "cipheringAlgorithm",
    "cipheringMasterKey",
    "signatureMasterKey"
})
public class CardProfile {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "KIC", required = true)
    protected KIC kic;
    @XmlElement(name = "KID", required = true)
    protected KID kid;
    @XmlElement(name = "SPI", required = true)
    protected SPI spi;
    @XmlElement(name = "TAR", required = true, type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    protected byte[] tar;
    @XmlElement(name = "SecurityBytesType", required = true)
    protected SecurityBytesType securityBytesType;
    @XmlElement(name = "SignatureAlgorithm", required = true)
    protected String signatureAlgorithm;
    @XmlElement(name = "CipheringAlgorithm", required = true)
    protected String cipheringAlgorithm;
    @XmlElement(name = "CipheringMasterKey", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] cipheringMasterKey;
    @XmlElement(name = "SignatureMasterKey", type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] signatureMasterKey;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }
    /**
     * Gets the value of the kic property.
     * 
     * @return
     *     possible object is
     *     {@link KIC }
     *     
     */
    public KIC getKIC() {
        return kic;
    }

    /**
     * Sets the value of the kic property.
     * 
     * @param value
     *     allowed object is
     *     {@link KIC }
     *     
     */
    public void setKIC(KIC value) {
        this.kic = value;
    }

    /**
     * Gets the value of the kid property.
     * 
     * @return
     *     possible object is
     *     {@link KID }
     *     
     */
    public KID getKID() {
        return kid;
    }

    /**
     * Sets the value of the kid property.
     * 
     * @param value
     *     allowed object is
     *     {@link KID }
     *     
     */
    public void setKID(KID value) {
        this.kid = value;
    }

    /**
     * Gets the value of the spi property.
     * 
     * @return
     *     possible object is
     *     {@link SPI }
     *     
     */
    public SPI getSPI() {
        return spi;
    }

    /**
     * Sets the value of the spi property.
     * 
     * @param value
     *     allowed object is
     *     {@link SPI }
     *     
     */
    public void setSPI(SPI value) {
        this.spi = value;
    }

    /**
     * Gets the value of the tar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getTAR() {
        return tar;
    }

    /**
     * Sets the value of the tar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTAR(byte[] value) {
        this.tar = ((byte[]) value);
    }

    /**
     * Gets the value of the securityBytesType property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityBytesType }
     *     
     */
    public SecurityBytesType getSecurityBytesType() {
        return securityBytesType;
    }

    /**
     * Sets the value of the securityBytesType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityBytesType }
     *     
     */
    public void setSecurityBytesType(SecurityBytesType value) {
        this.securityBytesType = value;
    }

    /**
     * Gets the value of the signatureAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureAlgorithm() {
        return signatureAlgorithm;
    }

    /**
     * Sets the value of the signatureAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureAlgorithm(String value) {
        this.signatureAlgorithm = value;
    }

    /**
     * Gets the value of the cipheringAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCipheringAlgorithm() {
        return cipheringAlgorithm;
    }

    /**
     * Sets the value of the cipheringAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCipheringAlgorithm(String value) {
        this.cipheringAlgorithm = value;
    }

    /**
     * Gets the value of the cipheringMasterKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getCipheringMasterKey() {
        return cipheringMasterKey;
    }

    /**
     * Sets the value of the cipheringMasterKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCipheringMasterKey(byte[] value) {
        this.cipheringMasterKey = ((byte[]) value);
    }

    /**
     * Gets the value of the signatureMasterKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getSignatureMasterKey() {
        return signatureMasterKey;
    }

    /**
     * Sets the value of the signatureMasterKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureMasterKey(byte[] value) {
        this.signatureMasterKey = ((byte[]) value);
    }
    
	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof CardProfile))
			return false;
		CardProfile other = (CardProfile) obj;
		if (name == null)
		{
			if (other.name != null)
				return false;
		}
		else if (!name.equals(other.name))
			return false;
		return true;
	}

	@Override
	public String toString()
	{
		StringBuilder builder = new StringBuilder();
		builder.append("CardProfile [name=");
		builder.append(name);
		builder.append(", kic=");
		builder.append(kic);
		builder.append(", kid=");
		builder.append(kid);
		builder.append(", spi=");
		builder.append(spi);
		builder.append(", tar=");
		builder.append(Util.toHexString(tar));
		builder.append(", securityBytesType=");
		builder.append(securityBytesType);
		builder.append(", signatureAlgorithm=");
		builder.append(signatureAlgorithm);
		builder.append(", cipheringAlgorithm=");
		builder.append(cipheringAlgorithm);
		builder.append(", cipheringMasterKey=");
		builder.append(Util.toHexString(cipheringMasterKey));
		builder.append(", signatureMasterKey=");
		builder.append(Util.toHexString(signatureMasterKey));
		builder.append("]");
		return builder.toString();
	}

}
