//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 04:14:20 PM MSD 
//

package org.opentelecoms.gsm0348.api.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "ResponsePacketStatus")
@XmlEnum
public enum ResponsePacketStatus {

  POR_OK,
  RC_CC_DS_FAILED,
  CNTR_LOW,
  CNTR_HIGH,
  CNTR_BLOCKED,
  CIPHERING_ERROR,
  UNIDENTIFIED_SECURITY_ERROR,
  INSUFFICIENT_MEMORY,
  MORE_TIME,
  TAR_UNKNOWN,
  INSUFFICIENT_SECURITY_LEVEL,
  TO_BE_SENT_VIA_SMS_SUBMIT,
  TO_BE_SENT_VIA_PROCESSUNSTRUCTUREDSS_REQUEST;

  public static ResponsePacketStatus fromValue(String v) {
    return valueOf(v);
  }

  public String value() {
    return name();
  }

}
