//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 04:14:20 PM MSD 
//


package ru.tapublog.lib.gsm0348.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KIC complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KIC">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="KeysetID" type="{ru.tapublog.lib.gsm0348}KeysetID"/>
 *         &lt;element name="CipheringAlgorithmMode" type="{ru.tapublog.lib.gsm0348}CipheringAlgorithmMode"/>
 *         &lt;element name="AlgorithmImplementation" type="{ru.tapublog.lib.gsm0348}AlgorithmImplementation"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KIC", propOrder = {

})
public class KIC implements Cloneable {

    @XmlElement(name = "KeysetID")
    protected byte keysetID;
    @XmlElement(name = "CipheringAlgorithmMode", required = true)
    protected CipheringAlgorithmMode cipheringAlgorithmMode;
    @XmlElement(name = "AlgorithmImplementation", required = true)
    protected AlgorithmImplementation algorithmImplementation;

    /**
     * Constructor for known KIc
     * 
     * @param KIc 
     *      byte for KIc
     */
    public void setValue(byte KIc) {
        keysetID = (byte) (KIc>>4);
        switch((byte)(KIc&0x3)) {
            case 0:
                algorithmImplementation = AlgorithmImplementation.ALGORITHM_KNOWN_BY_BOTH_ENTITIES;
                break;
            case 1:
                algorithmImplementation = AlgorithmImplementation.DES;
                break;
            case 2:
                algorithmImplementation = AlgorithmImplementation.RESERVED;
                break;
            case 3:
                algorithmImplementation = AlgorithmImplementation.PROPRIETARY_IMPLEMENTATIONS;
                break;
        }

        switch((byte)((KIc>>2)&0x3)) {
            case 0:
                cipheringAlgorithmMode = CipheringAlgorithmMode.DES_CBC;
                break;
            case 1:
                cipheringAlgorithmMode = CipheringAlgorithmMode.TRIPLE_DES_CBC_2_KEYS;
                break;
            case 2:
                cipheringAlgorithmMode = CipheringAlgorithmMode.TRIPLE_DES_CBC_3_KEYS;
                break;
            case 3:
                cipheringAlgorithmMode = CipheringAlgorithmMode.DES_ECB;
                break;
        }
    }
    
    /*
     * Return byte of KIc
     * 
     */
    public byte getValue() {
        byte KIc = 0;
        
        switch(algorithmImplementation) {
            case ALGORITHM_KNOWN_BY_BOTH_ENTITIES:
                KIc |= 0x00;
                break;
            case DES:
                KIc |= 0x01;
                break;
            case RESERVED:
                KIc |= 0x02;
                break;
            case PROPRIETARY_IMPLEMENTATIONS:
                KIc |= 0x03;
                break;
        }

        switch(cipheringAlgorithmMode) {
            case DES_CBC:
                KIc |= 0x00;
                break;
            case TRIPLE_DES_CBC_2_KEYS:
                KIc |= 0x01<<2;
                break;
            case TRIPLE_DES_CBC_3_KEYS:
                KIc |= 0x02<<2;
                break;
            case DES_ECB:
                KIc |= 0x03<<2;
                break;
        }
        KIc |= keysetID<<4;
        
        return KIc;
    }
    
    /**
     * Gets the value of the keysetID property.
     * 
     */
    public byte getKeysetID() {
        return keysetID;
    }

    /**
     * Sets the value of the keysetID property.
     * 
     */
    public void setKeysetID(byte value) {
        this.keysetID = value;
    }

    /**
     * Gets the value of the cipheringAlgorithmMode property.
     * 
     * @return
     *     possible object is
     *     {@link CipheringAlgorithmMode }
     *     
     */
    public CipheringAlgorithmMode getCipheringAlgorithmMode() {
        return cipheringAlgorithmMode;
    }

    /**
     * Sets the value of the cipheringAlgorithmMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CipheringAlgorithmMode }
     *     
     */
    public void setCipheringAlgorithmMode(CipheringAlgorithmMode value) {
        this.cipheringAlgorithmMode = value;
    }

    /**
     * Gets the value of the algorithmImplementation property.
     * 
     * @return
     *     possible object is
     *     {@link AlgorithmImplementation }
     *     
     */
    public AlgorithmImplementation getAlgorithmImplementation() {
        return algorithmImplementation;
    }

    /**
     * Sets the value of the algorithmImplementation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgorithmImplementation }
     *     
     */
    public void setAlgorithmImplementation(AlgorithmImplementation value) {
        this.algorithmImplementation = value;
    }

	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((algorithmImplementation == null) ? 0 : algorithmImplementation.hashCode());
		result = prime * result + ((cipheringAlgorithmMode == null) ? 0 : cipheringAlgorithmMode.hashCode());
		result = prime * result + keysetID;
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof KIC))
			return false;
		KIC other = (KIC) obj;
		if (algorithmImplementation != other.algorithmImplementation)
			return false;
		if (cipheringAlgorithmMode != other.cipheringAlgorithmMode)
			return false;
		if (keysetID != other.keysetID)
			return false;
		return true;
	}

	@Override
	public String toString()
	{
		StringBuilder builder = new StringBuilder();
		builder.append("KIC [keysetID=");
		builder.append(keysetID);
		builder.append(", cipheringAlgorithmMode=");
		builder.append(cipheringAlgorithmMode);
		builder.append(", algorithmImplementation=");
		builder.append(algorithmImplementation);
		builder.append("]");
		return builder.toString();
	}
    
    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}
