//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.09 at 04:14:20 PM MSD 
//


package ru.tapublog.lib.gsm0348.api.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SPI complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SPI">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="CommandSPI" type="{ru.tapublog.lib.gsm0348}CommandSPI"/>
 *         &lt;element name="ResponseSPI" type="{ru.tapublog.lib.gsm0348}ResponseSPI"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPI", propOrder = {

})
public class SPI implements Cloneable {

    @XmlElement(name = "CommandSPI", required = true)
    protected CommandSPI commandSPI;
    @XmlElement(name = "ResponseSPI", required = true)
    protected ResponseSPI responseSPI;
    
    public void setValue(byte[] SPIValue) {
        commandSPI = new CommandSPI();
        commandSPI.setValue(SPIValue[0]);
        responseSPI = new ResponseSPI();
        responseSPI.setValue(SPIValue[1]);
    }
    
    public byte[] getValue() {
        byte[] SPI = new byte[2];
        SPI[0] = commandSPI.getValue();
        SPI[1] = responseSPI.getValue();
        return SPI;
    }

    /**
     * Gets the value of the commandSPI property.
     * 
     * @return
     *     possible object is
     *     {@link CommandSPI }
     *     
     */
    public CommandSPI getCommandSPI() {
        return commandSPI;
    }

    /**
     * Sets the value of the commandSPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommandSPI }
     *     
     */
    public void setCommandSPI(CommandSPI value) {
        this.commandSPI = value;
    }

    /**
     * Gets the value of the responseSPI property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseSPI }
     *     
     */
    public ResponseSPI getResponseSPI() {
        return responseSPI;
    }

    /**
     * Sets the value of the responseSPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseSPI }
     *     
     */
    public void setResponseSPI(ResponseSPI value) {
        this.responseSPI = value;
    }

	@Override
	public int hashCode()
	{
		final int prime = 31;
		int result = 1;
		result = prime * result + ((commandSPI == null) ? 0 : commandSPI.hashCode());
		result = prime * result + ((responseSPI == null) ? 0 : responseSPI.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof SPI))
			return false;
		SPI other = (SPI) obj;
		if (commandSPI == null)
		{
			if (other.commandSPI != null)
				return false;
		}
		else if (!commandSPI.equals(other.commandSPI))
			return false;
		if (responseSPI == null)
		{
			if (other.responseSPI != null)
				return false;
		}
		else if (!responseSPI.equals(other.responseSPI))
			return false;
		return true;
	}

	@Override
	public String toString()
	{
		StringBuilder builder = new StringBuilder();
		builder.append("SPI [commandSPI=");
		builder.append(commandSPI);
		builder.append(", responseSPI=");
		builder.append(responseSPI);
		builder.append("]");
		return builder.toString();
	}

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }
}
